# Iceberg packages
# spark.jars.packages                org.apache.iceberg:iceberg-spark-runtime-4.0_2.13:1.10.1

# Iceberg extensions
spark.sql.extensions               org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions

# Spark catalog (Hive-backed)
spark.sql.catalog.spark_catalog                    org.apache.iceberg.spark.SparkSessionCatalog
spark.sql.catalog.spark_catalog.type               hive

# Local catalog (Hadoop-backed)
spark.sql.catalog.local                            org.apache.iceberg.spark.SparkCatalog
spark.sql.catalog.local.type                       hadoop
spark.sql.catalog.local.warehouse                  /opt/spark/warehouse
spark.sql.defaultCatalog                           local
spark.sql.catalogImplementation                    in-memory
spark.sql.catalog.local.cache-enabled              false

spark.driver.extraJavaOptions   -Dlog4j.rootCategory=ERROR,console
spark.executor.extraJavaOptions -Dlog4j.rootCategory=ERROR,console
